### ISSUE TITLE
Progeny.run scaling error

### ISSUE THREAD

**Issue by 321356766** [saezlab/progeny-py#1]
I keep getting the following scaling error when running progeny. It occurs using my own data, as well as following the tutorial exactly as described in the example notebook. 

Just to be clear, the input into progeny from an anndata object would be the adata.raw.X as a sparse matrix, correct? 

Thank you

progeny.run(adata, scale=True, organism="Human", top=100)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-48-1a918b6cbb5f> in <module>
----> 1 progeny.run(adata, scale=True, organism="Human", top=100)

C:\ProgramData\Anaconda3\lib\site-packages\progeny\progeny.py in run(data, scale, organism, top, inplace)
    101 
    102     assert df.shape[1] <= 1 and scale, \
--> 103     'If there is only one observation no scaling can be performed!'
    104 
    105     # Get progeny model

AssertionError: If there is only one observation no scaling can be performed!

**Comment by PauBadiaM** [comment]
Hi @321356766 ,

Yes sorry, that was a bug that I added in the last commit, should be fixed now. 
> Just to be clear, the input into progeny from an anndata object would be the adata.raw.X as a sparse matrix, correct?

That is correct, yes

Please, run `pip install --upgrade git+https://github.com/saezlab/progeny-py.git` and try again, let me know if your problem is solved.

**Comment by 321356766** [comment]
Works great. Thank you for your efforts.
